ciphertext=['DLHDRXHLLDLBRXHLLKSMFVRDNHXXVDLRWFHAYCHDLCYAKXHMGKXXHMFQKMRKNDODNRSYIXKCFYIKMYXZKAMRKNDODKAIVFQKDLDFDHXMFHFKHLABYHXDLNYLFSHMFFYFQYMKDLGQDNAFQKSKDMLYDLRWFAYCHDLMRKNDODKAMWNQRXHLLKSMHSKNHXXKAAYCHDLDLAKRKLAKLFFYKCRQHMDFQKOHNFFQHFFQKVNHLMYXZKRXHLLDLBRSYIXKCMOSYCHGDAKSHLBKYOAYCHDLMFVRDNHXKPHCRXKMYOAYCHDLMHSKIXYNUMFHNUDLBXYBDMFDNMGYSUOXYGCHLHBKCKLFHLASYIYFFHMURXHLLDLBQKLNKHMDLBXKAYCHDLDLAKRKLAKLFRXHLLKSNHLIKWMKAFYMYXZKRXHLLDLBRSYIXKCMDLHXXFQKMKZHSDYWMAYCHDLYLFQKYFQKSQHLAHSYWFKRXHLLKSDMFVRDNHXYOHAYCHDLMRKNDODNRXHLLKS']';
tabulate(ciphertext)
str='DLHDRXHLLDLBRXHLLKSMFVRDNHXXVDLRWFHAYCHDLCYAKXHMGKXXHMFQKMRKNDODNRSYIXKCFYIKMYXZKAMRKNDODKAIVFQKDLDFDHXMFHFKHLABYHXDLNYLFSHMFFYFQYMKDLGQDNAFQKSKDMLYDLRWFAYCHDLMRKNDODKAMWNQRXHLLKSMHSKNHXXKAAYCHDLDLAKRKLAKLFFYKCRQHMDFQKOHNFFQHFFQKVNHLMYXZKRXHLLDLBRSYIXKCMOSYCHGDAKSHLBKYOAYCHDLMFVRDNHXKPHCRXKMYOAYCHDLMHSKIXYNUMFHNUDLBXYBDMFDNMGYSUOXYGCHLHBKCKLFHLASYIYFFHMURXHLLDLBQKLNKHMDLBXKAYCHDLDLAKRKLAKLFRXHLLKSNHLIKWMKAFYMYXZKRXHLLDLBRSYIXKCMDLHXXFQKMKZHSDYWMAYCHDLYLFQKYFQKSQHLAHSYWFKRXHLLKSDMFVRDNHXYOHAYCHDLMRKNDODNRXHLLKS'
c='DLHDRX HLL DLB RXHLLKSMFVRDNHXXVDLRWFH AYCHDL CYAKXHMGKXXHMFQKMRKNDODNRSYIXKCFYIKMYXZKAMRKNDODKAIVFQKDLDFDHXMFHFKHLABYHXDLNYLFSHMFFYFQYMKDLGQDNAFQKSKDMLYDLRWF AYCHDL MRKNDODKAMWNQRXHLLKSMHSKNHXXKA AYCHDL DLAKRKLAKLFFYKCRQHMDFQKOHNFFQHFFQKVNHLMYXZKRXHLLDLBRSYIXKCMOSYCHGDAKSHLBKYOAYCHDLMFVRDNHXKPHCRXKMYOAYCHDLMHSKIXYNUMFHNUDLBXYBDMFDNMGYSUOXYGCHLHBKCKLFHLASYIYFFHMURXHLLDLBQKLNKHMDLBXKAYCHDLDLAKRKLAKLFRXHLLKSNHLIKWMKAFYMYXZKRXHLLDLBRSYIXKCMDLHXXFQKMKZHSDYWMAYCHDLYLFQKYFQKSQHLAHSYWFKRXHLLKSDMFVRDNHXYOHAYCHDLMRKNDODNRXHLLKS'
str = strrep(str,'K','e')  %单字符出现率最高的是L和K，可能对应e和t，出现率最低的是P，可能对应z或x。经过尝试发现K对应t或P对应z无法得到有意义的解，故将K对应e，P对应x
str = strrep(str,'P','x')
str = strrep(str,'D','i')  %通过观察得知AYCHDL频繁出现,DL出现23次,DL替换成in
str = strrep(str,'L','n')  

str = strrep(str,'R','p')  %通过观察RXHnninB  RXHnneS像planning和planner
str = strrep(str,'X','l')  
str = strrep(str,'H','a')  
str = strrep(str,'B','g')  
str = strrep(str,'S','r')  

str = strrep(str,'A','d') %观察得inAepenAenF和independent相似
str = strrep(str,'F','t')  

str = strrep(str,'C','m')  
str = strrep(str,'Y','o')  

str = strrep(str,'M','s')  %aMGellaM推测为as well as
str = strrep(str,'G','w')  

str = strrep(str,'I','b')  %proIlem推测为problem
str = strrep(str,'Q','h')  %as well as tQe 推测为the
str = strrep(str,'Z','v')  %problem to be solved solZe推测为solve  

str = strrep(str,'N','c')  %speNiOiN推测为specific
str = strrep(str,'O','f')  

str = strrep(str,'V','y')  %tVpicallV推测为typically

str = strrep(str,'W','u')  %inpWt,sWch推测为input，such